/**
 * textProcessing.js
 * ─────────────────
 * Text utility helpers: truncation, word count, report generation.
 */

/**
 * Truncate a string to maxLen characters, appending ellipsis if needed.
 * @param {string} text
 * @param {number} maxLen
 * @returns {string}
 */
export function truncate(text, maxLen = 120) {
  if (!text) return '';
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen - 3).trimEnd() + '…';
}

/**
 * Count words in a string.
 * @param {string} text
 * @returns {number}
 */
export function wordCount(text) {
  return (text || '').trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Build a plain-text validation report for download/copy.
 * @param {object} result  - Full result from runValidation()
 * @returns {string}
 */
export function buildTextReport(result) {
  const lines = [
    '═══════════════════════════════════════════════════════════',
    '         AI RESPONSE VALIDATION REPORT',
    '═══════════════════════════════════════════════════════════',
    `Date     : ${new Date(result.timestamp).toLocaleString()}`,
    `Query    : ${result.query}`,
    '',
    '── OVERALL RESULT ──────────────────────────────────────────',
    `Reliability Score : ${result.overallScore}/100`,
    `Supported Claims  : ${result.stats.supported}`,
    `Unsupported Claims: ${result.stats.unsupported}`,
    `Contradictory     : ${result.stats.contradictory}`,
    `Uncertain         : ${result.stats.uncertain}`,
    `Hallucination Risk: ${result.stats.hallucinationRisk}%`,
    '',
    '── SUMMARY ─────────────────────────────────────────────────',
    result.summary,
    '',
    '── CLAIM-LEVEL ANALYSIS ────────────────────────────────────',
  ];

  for (const claim of result.claims) {
    lines.push('');
    lines.push(`Claim #${claim.id}: ${claim.text}`);
    lines.push(`Status     : ${claim.status.toUpperCase()}`);
    lines.push(`Confidence : ${claim.confidencePct}%`);
    lines.push(`Evidence   : ${claim.evidence}`);
    lines.push(`Explanation: ${claim.explanation}`);
    lines.push('---');
  }

  lines.push('');
  lines.push('═══════════════════════════════════════════════════════════');
  lines.push('Generated by AI Response Validation System');
  lines.push('═══════════════════════════════════════════════════════════');

  return lines.join('\n');
}

/**
 * Build a JSON report object for download.
 * @param {object} result
 * @returns {string} JSON string
 */
export function buildJsonReport(result) {
  return JSON.stringify(result, null, 2);
}
